on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 11 * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo $PWD
  
      - name: check yaml files
        run: |
          python check_yaml_files.py https://raw.githubusercontent.com/open-data/ckanext-canada/master/ckanext/canada/tables/

      - name: get tables parquet
        run: |
          python fetch_ckan_2_parquet.py
         
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "generated"
          git push -f origin master
